name: cindy healthcheck
on:
  workflow_dispatch:
  schedule:
    - cron: '15 * * * *'

jobs:
  healthcheck:
    runs-on: ubuntu-latest
    steps:
      - name: URL healthcheck
        uses: jtalk/url-health-check-action@v4
        with:
          url: ${{ secrets.TARGET_URLS }}
      - name: Discord Webhook
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        if: failure()
        with:
          args: 'Healthcheck failed'
