name: cindy healthcheck
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch
jobs:
  healthcheck:
    runs-on: ubuntu-latest
    steps:
      - name: URL healthcheck
        uses: jtalk/url-health-check-action@v4
        with:
          url: ${{ secrets.TARGET_URLS }}
      - name: Discord Webhook
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Healthcheck failed'
